
spring:
  application:
    name: siteweb
  datasource: 
    url: jdbc:mysql://localhost:3306/siteweb
    username: root
    password: "Asyst@2016"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true 
