
spring:
  application:
    name: siteweb
  datasource: 
    url: jdbc:mysql://localhost:3306/siteweb
    username: siteweb
    password: faraja123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true 
